# Reusable workflow for PRs; to eject, you can replace this file with
# https://github.com/ryansonshine/ryansonshine/blob/main/.github/workflows/pr.yml
name: Pull Request

on: [pull_request]

jobs:
  build:
    uses: ryansonshine/ryansonshine/.github/workflows/pr.yml@81ff5a5296b61b77d8e6543f16f1fc81824b7839 # main
